format_version: 2
pipelines:
  pipeline_code_demo:
    group: defaultGroup
    materials:
      backend:
        git: https://github.com/arthisiva451/gocd-pipeline.git
        branch: master
    stages:
      - Build_Demo_Project_Stage:
          clean_workspace: true
          jobs:
            build_task:
              tasks:
                - exec:
                    run_if: passed
                    command: ls
                    arguments:
                    - package
     